sudo: false
language: c

matrix:
  include:
    - env: CABALVER=1.24 GHCVER=8.0.2

cache:
  directories:
  - $HOME/.stack
  

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:${HOME}/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack setup
  - stack install

script:
  - stack test
  
after_install:
