sudo: false

ghc
  - 7.10

env:
  - CABALVER=1.22 GHCVER=7.10.3 QC=QuichCheck-2.8.1 CRITERION=Criterion-1.1.1.0

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:/opt/ghc/7.10.3/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.3

script:
  - ./travis.sh
